### ISSUE TITLE
Emitter client library for Flutter

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#217]
Hi,
I created an emitter client library for Flutter.

You can find the source file in the following link:

https://gist.github.com/postacik/ac238af7e50fdb685551783fc37a4717

And here is a part of the sample code which uses the library:

https://gist.github.com/postacik/2f0685c9f62347f1890f7cdc1b1bd1f8

The library uses Dart mqtt_client library so you have to add it to your dependencies in pubspec.yaml file:

```
dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^5.5.2 

```

I hope it helps other Flutter developers.
