### ISSUE TITLE
SSL configuration in EKS

### ISSUE THREAD

**Issue by jreyeshdez** [emitter-io/emitter#299]
I have been trying to use SSL in EKS by using a certificate from AWS however I cant reach the broker at 8883 (MQTTS) but I can in 1883. It would be great to see a demo of this if possible. There are no errors in the brokers logs.

- tcp://mqtt.domain.io:1883 --> works
- ssl://mqtt.domain.io:8883 --> does not work - it hangs

In broker yaml I have ports:
```
containers:
      - env:
        ....
        - name: EMITTER_LISTEN
          value: ":1883"
        - name: EMITTER_TLS_LISTEN
          value: ":8883"
        - name: EMITTER_TLS_HOST
          value: "domain.io"
        - name: EMITTER_TLS_EMAIL
          value: "email@domain.io"
ports:
          - containerPort: 8080
          - containerPort: 8883
          - containerPort: 1883
          - containerPort: 443
          - containerPort: 4000
          - containerPort: 80
```
and in the load balancer yaml:
```
metadata:
  name: broker-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "certificateArn"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "8883"
...
ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
    - port: 80
      targetPort: 80
      name: http
```
Am I missing something?

I am not sure if the load balancer requieres the annotations part, but I also removed them to see if it works but it didnt.

Emitter logs:
```
...
2019/12/23 18:10:40 [service] starting the listener (0.0.0.0:1883)
2019/12/23 18:10:40 [service] starting the listener (0.0.0.0:8080)
2019/12/23 18:10:40 [tls] setting up certificates with dircache cache
2019/12/23 18:10:40 [service] exposing autocert TLS validation on :80
2019/12/23 18:10:40 [service] starting the listener (0.0.0.0:8883)
2019/12/23 18:10:40 [service] service started
...
```
Running netstat in the pods:

- broker-0:
```
kubectl exec -it broker-0 -- sh
~ # netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 broker-0.broker.default.svc.cluster.local:39417 broker-1.broker.default.svc.cluster.local:4000 ESTABLISHED 
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62668 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62564 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6950 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6934 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62576 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6948 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62610 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62674 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6958 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62594 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6956 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62612 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62608 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62574 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62566 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6920 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62614 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6936 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62624 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62584 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62618 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62570 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6910 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6926 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6918 TIME_WAIT   
tcp        0      0 broker-0.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6942 TIME_WAIT   
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node Path
```
- broker-1:
```
kubectl exec -it broker-1 -- sh
~ # netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62664 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6954 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62622 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:afs3-prserver TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6982 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:7010 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:afs3-kaserver TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6940 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:4000 broker-0.broker.default.svc.cluster.local:39417 ESTABLISHED 
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:afs3-update TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6988 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6938 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6928 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6924 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62666 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-193-164.ec2.internal:62636 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6932 TIME_WAIT   
tcp        0      0 broker-1.broker.default.svc.cluster.local:8883 ip-10-0-128-108.ec2.internal:6996 TIME_WAIT   
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node Path
```
