### ISSUE TITLE
Error on publish received security key provided is not authorized

### ISSUE THREAD

**Issue by patriotphoenix** [emitter-io/emitter#328]
Hello, 

I have started emitter on docker running on a public facing IP address and am able to successfully visit `https://<ip>/keygen` and enter in the secret key and receive a channel specific key, however when I am trying to publish a message using `ruby-mqtt` I am getting an error in the docker logs of emitter stating `[conn] error during publish received (the security key provided is not authorized to perform this operation)`. 

I am attempting to connect to `emitter` via `ruby-mqtt` from my local development machine's docker container to a docker container on digitalocean. 

Mac Host 
-> Docker Container
-> -> Ruby MQTT Client Connection 
```ruby
client = MQTT::Client.connect(
  :host => "mydomain.com",
  :port => 443,
  :ssl => true,
  :cert_file => "/opt/emitter_certs/public.pem",
  :key_file => "/opt/emitter_certs/private.pem",
  :ca_file => "/opt/emitter_certs/public.ca-bundle"
)
```

DigitalOcean
-> Virtual Machine
-> -> Docker Container 
-> -> -> emitter running with emitter.json config file
```json
{
    "listen": ":8080",
    "license": "<generated license>",
    "tls": {
        "listen": ":443",
        "host": "mydomain.com",
        "certificate": "cert.pem",
        "private": "key.pem"
    },
    "storage": {
        "provider": "inmemory"
    }
}
```

When I run `docker logs -f <container-id>` on the VM I get: 
```
2020/07/15 07:59:48 [service] received signal terminated, exiting...
2020/07/15 08:01:34 [service] configured logging provider (stderr)
2020/07/15 08:01:34 [service] configured message storage (inmemory)
2020/07/15 08:01:34 [service] configured usage metering (noop)
2020/07/15 08:01:34 [service] configured contracts provider (single)
2020/07/15 08:01:34 [service] configured monitoring sink (self)
2020/07/15 08:01:34 [service] configured node name (02:42:ac:12:00:02)
2020/07/15 08:01:34 [service] starting the listener (0.0.0.0:8080)
2020/07/15 08:01:34 [tls] setting up certificates with dircache cache
2020/07/15 08:01:34 [service] starting the listener (0.0.0.0:443)
2020/07/15 08:01:34 [service] service started
```

The docker container is being deployed using `docker-compose` which can be seen here: 
```yaml
version: '3.4'
services:
  emitter:
    image: emitter/server
    ports:
      - 8080:8080
      - 443:443
    expose:
      - 443
      - 8080
    volumes:
      - /root/emitter/certs/mydomain_com.crt:/root/cert.pem:ro
      - /root/emitter/certs/mydomain_com.key:/root/key.pem:ro
      - /root/emitter/emitter.json:/root/emitter.json
    entrypoint: "./emitter --config /root/emitter.json"
    restart: unless-stopped

```

When I connect to the `https://mydomain.com/keygen` and enter in the `Secret Key` and `/announcements/` as the channel name with all options selected except for the last, I get a string response on the screen that looks like: 

```
channel: /announcements/
key    : MY_NEW_KEY_HERE
```

When I attempt to run the following `ruby-mqtt` call: 
```ruby
client.publish("MY_NEW_KEY_HERE/announcements/", "Hello world!")
client.disconnect()
```

I get an error message in the `docker logs -f <emitter-container-id>` that says: 
```
2020/07/15 08:05:26 [conn] error during publish received (the security key provided is not authorized to perform this operation)
```

*MY QUESTION*: Is it possible that my requests are being rejected because of the domain / ip from which the requests are being made from? `localhost` doesn't match `mydomain.com`. I feel like I am missing something basic, or perhaps its a client issue with the `ruby-mqtt` gem? But the request is exceptionally basic here. 

Any guidance that can be provided would be greatly appreciated. 

Thank you!
